{
  "name": "extendo-error",
  "version": "1.0.1",
  "description": "Safely and simply extend native Error with prototype chaining support",
  "main": "src/extendo-error.js",
  "typings": "src/extendo-error.d.ts",
  "scripts": {
    "build": "tsc",
    "build-with-maps": "tsc --sourceMap",
    "review": "tslint \"./**/*.ts\" --exclude \"./**/*.d.ts\" --exclude \"./node_modules/**/*.ts\"",
    "pretest": "npm run build-with-maps",
    "test": "npm run review && npm run unit-tests",
    "unit-tests": "nyc --reporter=lcov --reporter=html alsatian \"./**/*.spec.js\" && nyc report",
    "prepublish": "npm test && npm run build"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/jamesrichford/extendo-error.git"
  },
  "keywords": [
    "extendo",
    "error",
    "extendable",
    "typescript",
    "prototype",
    "chaining",
    "extend error",
    "instanceof"
  ],
  "author": "James Richford",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/jamesrichford/extendo-error/issues"
  },
  "homepage": "https://github.com/jamesrichford/extendo-error#readme",
  "devDependencies": {
    "alsatian": "^1.0.0-beta.4",
    "codeclimate-test-reporter": "^0.4.0",
    "coveralls": "^2.11.15",
    "nyc": "^10.0.0",
    "tslint": "^4.0.2",
    "typescript": "^2.1.4"
  }
}
